export const STORAGE_KEY = "golden-cane-items-v1";

export const defaultItems = {
  "cold-medicine": {
    id: "cold-medicine",
    name: "感冒药",
    type: "药品",
    ownerHint: "白色药盒，放在客厅抽屉",
    intro: "这是感冒药。",
    introAudio: "",
    usage: "用于缓解鼻塞、流鼻涕和轻度发热。",
    usageAudio: "",
    cautions: "请按说明服用。服药后如果困倦，请避免外出独行。",
    cautionsAudio: "",
    notes: "这盒药是早上新买的，还没有开封。",
    notesAudio: "",
    deviceName: "BLE-感冒药-01",
    ringServiceUuid: "",
    ringCharacteristicUuid: "",
    ringHex: "01",
    paired: true,
    nfcTitle: "感冒药",
    nfcPath: "/item/cold-medicine",
    lastKnownBleName: "BLE-感冒药-01",
  },
  "black-coat": {
    id: "black-coat",
    name: "黑色外套",
    type: "衣物",
    ownerHint: "挂在卧室门后",
    intro: "这是黑色外套。",
    introAudio: "",
    usage: "适合外出时保暖穿着。",
    usageAudio: "",
    cautions: "口袋里可能有钥匙，请先检查再清洗。",
    cautionsAudio: "",
    notes: "左袖口有一个触感明显的小纽扣，方便和其他外套区分。",
    notesAudio: "",
    deviceName: "BLE-黑外套-02",
    ringServiceUuid: "",
    ringCharacteristicUuid: "",
    ringHex: "01",
    paired: true,
    nfcTitle: "黑色外套",
    nfcPath: "/item/black-coat",
    lastKnownBleName: "BLE-黑外套-02",
  },
  "blood-pressure-medicine": {
    id: "blood-pressure-medicine",
    name: "降压药",
    type: "药品",
    ownerHint: "床头柜右侧",
    intro: "这是降压药。",
    introAudio: "",
    usage: "用于日常控制血压。",
    usageAudio: "",
    cautions: "需要按医生建议定时服用，不要自行增减剂量。",
    cautionsAudio: "",
    notes: "瓶身有圆形防滑贴，方便手摸辨认。",
    notesAudio: "",
    deviceName: "BLE-降压药-03",
    ringServiceUuid: "",
    ringCharacteristicUuid: "",
    ringHex: "01",
    paired: true,
    nfcTitle: "降压药",
    nfcPath: "/item/blood-pressure-medicine",
    lastKnownBleName: "BLE-降压药-03",
  },
};
